# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: test

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ASPNETCORE_APPCONFIG__SHEETID: ${{ secrets.ASPNETCORE_APPCONFIG__SHEETID }}
      ASPNETCORE_APPCONFIG__SHEETSURL: ${{ secrets.ASPNETCORE_APPCONFIG__SHEETSURL }}
      TEST_RESULTS_PATH: "/home/runner/work/StpFoodBlazor/StpFoodBlazor/StpFoodBlazor/StpFoodBlazorTest/TestResults"

    steps:
    - uses: actions/checkout@v4
    # need to uncomment this if you want to run act
    # - uses: browser-actions/setup-chrome@v1
    #   with:
    #     install-chromedriver: true
    #     install-dependencies: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    # single step so app server logs will stream to the console during test run
    - name: Test
      run: |
        dotnet run --project StpFoodBlazor/StpFoodBlazor/StpFoodBlazor.csproj --no-build &
        sleep 10  &&
        dotnet test --settings ../StpFoodBlazor/StpFoodBlazor/StpFoodBlazorTest/tests.runsettings --no-build --collect "XPlat Code Coverage"
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.4.4
      if: always()
      continue-on-error: true
      with:
        reports: "${{ env.TEST_RESULTS_PATH }}/**/coverage.cobertura.xml"
        targetdir: "${{ env.TEST_RESULTS_PATH }}/coveragereport"
        reporttypes: Html;Html_Dark
    - name: Copy coverage report due to Irongut bug
      if: always()
      run: |
        mkdir -p ./coverage &&
        ls -ltra "${{ env.TEST_RESULTS_PATH }}/**/ &&
        cp "${{ env.TEST_RESULTS_PATH }}/**/coverage.cobertura.xml" ./coverage/coverage.cobertura.xml
    - name: Code Coverage Analysis
      uses: irongut/CodeCoverageSummary@v1.3.0
      if: always()
      with:
        filename: coverage/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '82 85'
    - name: Upload HTML coverage report
      uses: actions/upload-artifact@v4
      if: always()
      continue-on-error: true
      with:
        name: Coverage Report HTML
        path: "${{ env.TEST_RESULTS_PATH }}/coveragereport"
    - name: Upload Cobertura XML
      uses: actions/upload-artifact@v4
      if: always()
      continue-on-error: true
      with:
        name: Cobertura
        path: "${{ env.TEST_RESULTS_PATH }}/**/coverage.cobertura.xml"
    - name: Upload Selenium screenshots
      uses: actions/upload-artifact@v4
      if: always()
      continue-on-error: true
      with:
        name: Selenium PNG
        path: "${{ env.TEST_RESULTS_PATH }}/*.png"
    - name: Upload Selenium HTML
      uses: actions/upload-artifact@v4
      if: always()
      continue-on-error: true
      with:
        name: Selenium HTML
        path: "${{ env.TEST_RESULTS_PATH }}/*.html"
