# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: test

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      ASPNETCORE_APPCONFIG__SHEETID: ${{ secrets.ASPNETCORE_APPCONFIG__SHEETID }}
      ASPNETCORE_APPCONFIG__SHEETSURL: ${{ secrets.ASPNETCORE_APPCONFIG__SHEETSURL }}
      TEST_RESULTS_PATH: "/home/runner/work/StpFoodBlazor/StpFoodBlazor/StpFoodBlazor/StpFoodBlazorTest/TestResults"
      MIN_LINE_COVERAGE: 87
      MIN_BRANCH_COVERAGE: 88

    steps:
    - uses: actions/checkout@v4
    # need to uncomment this if you want to run act
    # - uses: browser-actions/setup-chrome@v1
    #   with:
    #     install-chromedriver: true
    #     install-dependencies: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    # single step so app server logs will stream to the console during test run
    - name: Test
      run: |
        dotnet run --project StpFoodBlazor/StpFoodBlazor/StpFoodBlazor.csproj --no-build &
        sleep 5  &&
        dotnet test --settings ../StpFoodBlazor/StpFoodBlazor/StpFoodBlazorTest/tests.runsettings \
        --no-build --collect "XPlat Code Coverage"
    - name: ReportGenerator with coverage gate
      uses: danielpalme/ReportGenerator-GitHub-Action@5.4.4
      if: always()
      with:
        reports: "${{ env.TEST_RESULTS_PATH }}/**/coverage.opencover.xml"
        targetdir: "${{ env.TEST_RESULTS_PATH }}/coveragereport"
        reporttypes: Html;Html_Dark
        title: 'StpFoodBlazor Test Coverage'
        tag: '${{ github.run_number }}_${{ github.run_id }}'
        customSettings: 'minimumCoverageThresholds:lineCoverage=${{ env.MIN_LINE_COVERAGE }};minimumCoverageThresholds:branchCoverage=${{ env.MIN_BRANCH_COVERAGE }}'
    - name: Print coverage percentage to console
      uses: insightsengineering/coverage-action@v2
      if: always()
      # This action will not fail, just used for printing the coverage percentage
      continue-on-error: true
      with:
        path: "${{ env.TEST_RESULTS_PATH }}/**/coverage.opencover.xml"
        threshold: 85
        coverage-summary-title: "StpFoodBlazor Coverage"
    - name: Upload HTML coverage report
      uses: actions/upload-artifact@v4
      if: always()
      continue-on-error: true
      with:
        name: coverage_report_html
        path: "${{ env.TEST_RESULTS_PATH }}/coveragereport"
    - name: Upload Opencover XML
      uses: actions/upload-artifact@v4
      if: always()
      continue-on-error: true
      with:
        name: coverage_report_xml
        path: "${{ env.TEST_RESULTS_PATH }}/**/coverage.opencover.xml"
    - name: Upload Selenium screenshots
      uses: actions/upload-artifact@v4
      if: always()
      continue-on-error: true
      with:
        name: selenium_png
        path: "${{ env.TEST_RESULTS_PATH }}/*.png"
    - name: Upload Selenium HTML
      uses: actions/upload-artifact@v4
      if: always()
      continue-on-error: true
      with:
        name: selenium_html
        path: "${{ env.TEST_RESULTS_PATH }}/*.html"
  sonar:
    name: SonarQube build and analyze
    needs: test
    runs-on: windows-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu' # Alternative distribution options are available.
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Cache SonarQube Cloud packages
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache SonarQube Cloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      - name: Install SonarQube Cloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
      - name: Download coverage xml
        uses: actions/download-artifact@v4
        with:
          name: coverage_report_xml
      - name: List coverage files
        shell: powershell
        run: |
          Write-Host "Looking for coverage files..."
          Get-ChildItem -Path . -Recurse -Filter "*.xml" | Where-Object { $_.Name -like "*coverage*" } | ForEach-Object { Write-Host $_.FullName }
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"eebbesen_StpFoodBlazor" /o:"eebbesen" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="**\coverage.opencover.xml" /d:sonar.scanner.skipJreProvisioning=true /d:sonar.verbose=true
          dotnet build
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
